import { db } from './db';
import { users, vendors, deals } from '../shared/schema';

export async function initializeDatabase() {
  try {
    // Insert demo users
    await db.insert(users).values([
      {
        username: 'admin',
        email: 'admin@instoredealz.com',
        password: 'admin123',
        role: 'admin',
        name: 'Admin User',
        phone: '+911234567890',
        city: 'Mumbai',
        state: 'Maharashtra',
        totalSavings: '0',
        dealsClaimed: 0,
      },
      {
        username: 'testvendor',
        email: 'vendor@test.com',
        password: 'vendor123',
        role: 'vendor',
        name: 'Test Vendor',
        phone: '+911234567891',
        city: 'Delhi',
        state: 'Delhi',
        totalSavings: '0',
        dealsClaimed: 0,
      },
      {
        username: 'testcustomer',
        email: 'customer@test.com',
        password: 'customer123',
        role: 'customer',
        name: 'Test Customer',
        phone: '+911234567892',
        city: 'Mumbai',
        state: 'Maharashtra',
        totalSavings: '0',
        dealsClaimed: 0,
      },
      {
        username: 'demo',
        email: 'demo@demo.com',
        password: 'demo123',
        role: 'customer',
        name: 'Demo Customer',
        phone: '+911234567893',
        city: 'Mumbai',
        state: 'Maharashtra',
        totalSavings: '0',
        dealsClaimed: 0,
      }
    ]).onConflictDoNothing();

    // Insert vendor records
    await db.insert(vendors).values([
      {
        userId: 2,
        businessName: 'Mumbai Electronics Store',
        gstNumber: 'GST123456789',
        panNumber: 'PAN123456789',
        address: '123 Electronics Street',
        city: 'Mumbai',
        state: 'Maharashtra',
        pincode: '400001',
        isApproved: true,
        rating: '4.5',
        totalDeals: 0,
        totalRedemptions: 0,
      },
      {
        userId: 3,
        businessName: 'Delhi Fashion Hub',
        gstNumber: 'GST987654321',
        panNumber: 'PAN987654321',
        address: '456 Fashion Plaza',
        city: 'Delhi',
        state: 'Delhi',
        pincode: '110001',
        isApproved: true,
        rating: '4.2',
        totalDeals: 0,
        totalRedemptions: 0,
      }
    ]).onConflictDoNothing();

    // Insert sample deals
    const validUntil = new Date();
    validUntil.setDate(validUntil.getDate() + 30);

    await db.insert(deals).values([
      {
        vendorId: 1,
        title: 'Summer Electronics Sale - 20% Off',
        description: 'Get 20% discount on all electronics and gadgets. Valid on smartphones, laptops, and accessories.',
        category: 'electronics',
        discountPercentage: 20,
        validUntil,
        maxRedemptions: 100,
        currentRedemptions: 0,
        isActive: true,
        isApproved: true,
        approvedBy: 1,
        address: '123 Electronics Street, Mumbai, Maharashtra 400001',
        verificationPin: '1234',
        requiredMembership: 'basic',
      },
      {
        vendorId: 1,
        title: 'Fashion Week Special - 30% Off',
        description: 'Exclusive 30% discount on latest fashion trends. Valid on clothing, shoes, and accessories.',
        category: 'fashion',
        discountPercentage: 30,
        validUntil,
        maxRedemptions: 50,
        currentRedemptions: 0,
        isActive: true,
        isApproved: true,
        approvedBy: 1,
        address: '456 Fashion Plaza, Mumbai, Maharashtra 400002',
        verificationPin: '5678',
        requiredMembership: 'basic',
      },
      {
        vendorId: 1,
        title: 'Food Festival - 25% Off',
        description: 'Delicious food deals! Get 25% off on your favorite meals and beverages.',
        category: 'food',
        discountPercentage: 25,
        validUntil,
        maxRedemptions: 200,
        currentRedemptions: 0,
        isActive: true,
        isApproved: true,
        approvedBy: 1,
        address: '789 Food Court, Mumbai, Maharashtra 400003',
        verificationPin: '9012',
        requiredMembership: 'basic',
      },
      {
        vendorId: 2,
        title: 'Travel Adventure - 40% Off',
        description: 'Amazing travel deals! 40% discount on weekend getaways and travel packages.',
        category: 'travel',
        discountPercentage: 40,
        validUntil,
        maxRedemptions: 30,
        currentRedemptions: 0,
        isActive: true,
        isApproved: true,
        approvedBy: 1,
        address: '321 Travel Agency, Mumbai, Maharashtra 400004',
        verificationPin: '3456',
        requiredMembership: 'premium',
      },
      {
        vendorId: 2,
        title: 'Home Decor Sale - 35% Off',
        description: 'Transform your home with 35% off on furniture, decor, and home essentials.',
        category: 'home',
        discountPercentage: 35,
        validUntil,
        maxRedemptions: 75,
        currentRedemptions: 0,
        isActive: true,
        isApproved: true,
        approvedBy: 1,
        address: '654 Home Store, Mumbai, Maharashtra 400005',
        verificationPin: '7890',
        requiredMembership: 'basic',
      },
      {
        vendorId: 1,
        title: 'Wellness & Fitness - 45% Off',
        description: 'Get fit with 45% off on gym memberships, yoga classes, and fitness equipment.',
        category: 'fitness',
        discountPercentage: 45,
        validUntil,
        maxRedemptions: 40,
        currentRedemptions: 0,
        isActive: true,
        isApproved: true,
        approvedBy: 1,
        address: '987 Fitness Center, Mumbai, Maharashtra 400006',
        verificationPin: '2468',
        requiredMembership: 'basic',
      },
      {
        vendorId: 2,
        title: 'Beauty & Spa - 50% Off',
        description: 'Pamper yourself with 50% off on beauty treatments, spa services, and cosmetics.',
        category: 'beauty',
        discountPercentage: 50,
        validUntil,
        maxRedemptions: 60,
        currentRedemptions: 0,
        isActive: true,
        isApproved: true,
        approvedBy: 1,
        address: '321 Beauty Salon, Mumbai, Maharashtra 400007',
        verificationPin: '1357',
        requiredMembership: 'basic',
      },
      {
        vendorId: 1,
        title: 'Services Special - 30% Off',
        description: 'Get 30% off on various services including repairs, maintenance, and consultations.',
        category: 'services',
        discountPercentage: 30,
        validUntil,
        maxRedemptions: 80,
        currentRedemptions: 0,
        isActive: true,
        isApproved: true,
        approvedBy: 1,
        address: '555 Service Center, Mumbai, Maharashtra 400008',
        verificationPin: '9753',
        requiredMembership: 'basic',
      }
    ]).onConflictDoNothing();

    console.log('Database initialized successfully with sample data');
  } catch (error) {
    console.error('Database initialization failed:', error);
  }
}